#!/usr/bin/env node

const fs = require('fs');
const jq = require('jq-stream');
const Progress = require('progress');
const notify = require('../libs/notify-api');
const meta = require('../libs/meta');

let names = [],
  total = require('../data/skimdb-size.json').total_rows,
  progress = new Progress('  Parsing [:bar] :percent :etas', {
    total: total,
    complete: '=',
    incomplete: ' ',
    width: 50
  });

jq('./data/skimdb.json', 'rows.*.value', each, end);

function each(pkg) {
  let pkgName = pkg.name; // 注意：有些 package 此字段不存在
  progress.tick({pkgName: truncate(pkgName, 30)});
  if (pkgName) {
    names.push(pkgName);
  }
}

function end() {
  // 记录真实的数组的长度（不要使用 total)
  meta.set('totalNpmPackages', names.length);

  fs.writeFileSync('./build/npm-names.json', JSON.stringify(names));

  console.log('\n\n  Finished !');
  notify.sendSuccess(meta.data);
}

function truncate(str, size, suffix) {
  str = typeof str === 'string' ? str : '';
  suffix = suffix || '...';

  size -= suffix.length;
  return str.length > size ? str.substr(0, size) + suffix : str;
}

