#!/usr/bin/env bash

set -x            # print each command before execution
set -o errexit    # always exit on error
set -o pipefail   # don't ignore exit codes when piping output
set -o nounset    # fail on unset variables

git config --global user.email "qiuzhongleiabc@126.com"
git config --global user.name "Mora"

# set up the repo
git clone https://github.com/program-bot/mora-bot.git
git clone https://github.com/program-bot/mora-bot-data.git

# build
cd mora-bot
npm run notify "mora-bot: 开始编译"
npm run build
npm test

# bail if no changes are present
[[ `git status --porcelain` ]] || (npm run notify "mora-bot: 文件没有变化，取消发布" && exit)

mv build/* ../mora-bot-data/
cp meta.json ../mora-bot-data/


# mora-bot-data 打 tag 并提交到 npm 上
cd mora-bot-data
git add . -A

git commit -m "mora-bot auto commit"
npm version minor -m "bump minor to %s"
npm publish
git push origin master --follow-tags


# mora-bot 只更新 meta.json 文件
cd ../mora-bot
git push origin master

npm run notify "mora-bot: 完成发布" -- --level SUCCESS

# clean up
cd ..
rm -rf mora-bot mora-bot-data
