#!/usr/bin/env bash

set -x            # print each command before execution
set -o errexit    # always exit on error
set -o pipefail   # don't ignore exit codes when piping output
set -o nounset    # fail on unset variables

# set up the repo
git clone https://github.com/program-bot/mora-bot.git
cd mora-bot
npm run build
npm test

# bail if no changes are present
[[ `git status --porcelain` ]] || exit

git add meta.json
git config user.email "qiuzhongleiabc@126.com"
git config user.name "Mora"
git commit -m "mora-bot auto commit"
npm version minor -m "bump minor to %s"
npm publish
git push origin master --follow-tags

# clean up
cd ..
rm -rf mora-bot
